[project]
name = "fastapi-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.116.1",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "streamlit>=1.49.1",
    "uvicorn==0.35.0",
]
